### ISSUE TITLE
Add support for global HTTP proxy config

### ISSUE THREAD

**Issue by anothertobi** [projectsyn/component-signalilo#2]
## Context

We have a K8s installation behind a proxy which is set up to use Signalilo and therefore requires the HTTP proxy settings to be configurable.
Other K8s installations which are behind a proxy have not used Signalilo and most components support the usage of `${global:http_proxy}`, `${global:https_proxy}` and `${global:no_proxy}`.

## Alternatives

The alternative would be to use Opsgenie instead of Icinga.

**Comment by anothertobi** [comment]
PR that implemented this for espejo: https://github.com/projectsyn/component-espejo/pull/16

**Comment by simu** [comment]
Looks like this got implemented in #3. @anothertobi is it ok to close this issue?

**Comment by mhutter** [comment]
Ah, forgot to mention this issue in the PR
